#!/usr/bin/env python3
"""Render Telegram-dark-theme previews from preview_ui.txt.

Reads the exact Persian copy from preview_ui.txt (generated by the real
formatting code). HTML is interpreted, never printed: <b> is bold,
<blockquote> is a quote bar, [buttons] become an inline keyboard.

Requires: Pillow, arabic-reshaper, python-bidi, Vazirmatn (and BASIC
layout so Pillow does not undo the reshape/bidi pass).
"""
from __future__ import annotations

import html
import re
from dataclasses import dataclass
from pathlib import Path

import arabic_reshaper
from bidi.algorithm import get_display
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "preview_ui.txt"
OUT1 = ROOT / "ui_preview.png"
OUT2 = ROOT / "ui_preview_2.png"

W = 1000
BG = "#12181f"
TOP = "#17212b"
BUBBLE = "#212c3a"
BUTTON = "#24303f"
TEXT = "#ffffff"
MUTED = "#b4c2d3"
SENDER = "#b95889"
QUOTE_BG = "#303142"
QUOTE_BAR = "#b95889"
DIVIDER = "#243241"
AVATAR = "#dc8df0"

FONT_REG = "/usr/share/fonts/truetype/vazirmatn/Vazirmatn-Regular.ttf"
FONT_MED = "/usr/share/fonts/truetype/vazirmatn/Vazirmatn-Medium.ttf"
FONT_BOLD = "/usr/share/fonts/truetype/vazirmatn/Vazirmatn-Bold.ttf"
BASIC = ImageFont.Layout.BASIC

F_REG = ImageFont.truetype(FONT_REG, 22, layout_engine=BASIC)
F_MED = ImageFont.truetype(FONT_MED, 22, layout_engine=BASIC)
F_BOLD = ImageFont.truetype(FONT_BOLD, 22, layout_engine=BASIC)
F_SENDER = ImageFont.truetype(FONT_MED, 20, layout_engine=BASIC)
F_TIME = ImageFont.truetype(FONT_REG, 16, layout_engine=BASIC)
F_CAPTION = ImageFont.truetype(FONT_MED, 17, layout_engine=BASIC)
F_BUTTON = ImageFont.truetype(FONT_MED, 20, layout_engine=BASIC)

EMOJI_COLORS = {
    "🟣": "#a936e8",
    "🟢": "#38c932",
    "🟡": "#ffd13b",
    "🟠": "#ef8b22",
}

BUBBLE_X = 92
BUBBLE_W = 760
PAD = 22
LINE_H = 31


def shape(text: str) -> str:
    """Arabic-shape and bidi-reorder a logical RTL string for Pillow."""
    return get_display(arabic_reshaper.reshape(text))


def visual_width(draw: ImageDraw.ImageDraw, logical: str, font: ImageFont.FreeTypeFont) -> float:
    vis = shape(logical)
    width = 0.0
    for part in re.split("([🟣🟢🟡🟠])", vis):
        if part in EMOJI_COLORS:
            width += 22
        elif part:
            width += draw.textlength(part, font=font)
    return width


def draw_rtl(
    draw: ImageDraw.ImageDraw,
    right: float,
    y: float,
    text: str,
    font: ImageFont.FreeTypeFont,
    fill: str = TEXT,
) -> None:
    """Right-align shaped Persian; draw color-circle emoji without tofu."""
    vis = shape(html.unescape(text))
    parts = re.split("([🟣🟢🟡🟠])", vis)
    widths = [22 if part in EMOJI_COLORS else draw.textlength(part, font=font) for part in parts]
    x = right - sum(widths)
    for part, width in zip(parts, widths):
        if part in EMOJI_COLORS:
            cy = y + 13
            draw.ellipse((x + 2, cy - 9, x + 20, cy + 9), fill=EMOJI_COLORS[part])
            draw.ellipse((x + 6, cy - 7, x + 13, cy - 3), fill="#ffffff55")
        elif part:
            draw.text((x, y), part, font=font, fill=fill)
        x += width


def wrap_rtl(
    draw: ImageDraw.ImageDraw, logical: str, font: ImageFont.FreeTypeFont, max_width: int
) -> list[str]:
    words = logical.split()
    if not words:
        return [""]
    out, cur = [], words[0]
    for word in words[1:]:
        candidate = f"{cur} {word}"
        if visual_width(draw, candidate, font) <= max_width:
            cur = candidate
        else:
            out.append(cur)
            cur = word
    out.append(cur)
    return out


@dataclass
class Row:
    text: str
    bold: bool = False
    quote: bool = False
    expandable: bool = False


def section(raw: str, number: str, title: str) -> str:
    heading = re.compile(rf"^{re.escape(number)}\) {re.escape(title)}\b.*$", re.M)
    match = heading.search(raw)
    if not match:
        raise RuntimeError(f"Section not found: {number}) {title}")
    start = raw.find("\n", match.end()) + 1
    start = raw.find("\n", start) + 1  # skip the ===== underline
    end_marker = re.search(r"^={20,}$", raw[start:], re.M)
    end = start + end_marker.start() if end_marker else len(raw)
    return raw[start:end].strip("\n")


def parse_rows(block: str) -> tuple[list[Row], list[str]]:
    rows: list[Row] = []
    buttons: list[str] = []
    in_buttons = False
    in_quote = False
    expandable = False
    for raw_line in block.splitlines():
        line = raw_line.strip()
        if line == "[buttons]":
            in_buttons = True
            continue
        if in_buttons:
            buttons.extend(re.findall(r"\[([^]]+)\]", line))
            continue
        if line.startswith("<blockquote"):
            in_quote = True
            expandable = "expandable" in line.split(">", 1)[0]
            line = line.split(">", 1)[1]
        closes = "</blockquote>" in line
        line = line.replace("</blockquote>", "")
        bold = line.startswith("<b>") and line.endswith("</b>")
        line = re.sub(r"</?b>", "", line)
        rows.append(Row(html.unescape(line), bold=bold, quote=in_quote, expandable=expandable))
        if closes:
            in_quote = False
            expandable = False
    return rows, buttons


def draw_tail(draw: ImageDraw.ImageDraw, x: int, bottom: int) -> None:
    draw.polygon([(x + 7, bottom - 26), (x + 7, bottom), (x - 7, bottom)], fill=BUBBLE)


def draw_avatar(draw: ImageDraw.ImageDraw, cy: int) -> None:
    draw.ellipse((20, cy - 25, 70, cy + 25), fill=AVATAR)
    draw.text((45, cy + 1), "C", font=F_MED, fill=TEXT, anchor="mm")


def prepare_rows(
    draw: ImageDraw.ImageDraw, rows: list[Row], *, collapsed_quote: bool
) -> list[tuple[Row, list[str]]]:
    content_w = BUBBLE_W - PAD * 2
    prepared: list[tuple[Row, list[str]]] = []
    quote_seen = 0
    for row in rows:
        if collapsed_quote and row.quote:
            quote_seen += 1
            if quote_seen > 2:
                continue
        font = F_BOLD if row.bold else F_REG
        extra = 18 if row.quote else 0
        prepared.append((row, wrap_rtl(draw, row.text, font, content_w - extra)))
    return prepared


def measure(prepared: list[tuple[Row, list[str]]], *, collapsed_quote: bool) -> int:
    body_h = 0
    prev_quote = False
    saw_quote = False
    for row, lines in prepared:
        if row.text == "":
            body_h += 16
            prev_quote = row.quote
            continue
        if row.quote and not prev_quote:
            body_h += 7
        body_h += LINE_H * len(lines)
        if prev_quote and not row.quote:
            body_h += 38 if collapsed_quote else 8
        prev_quote = row.quote
        saw_quote = saw_quote or row.quote
    if collapsed_quote and saw_quote and prev_quote:
        body_h += 30
    return 48 + body_h + 34


def quote_span(
    y: int, prepared: list[tuple[Row, list[str]]], *, collapsed_quote: bool
) -> tuple[int, int] | None:
    cy = y + 45
    q_start = q_end = None
    for row, lines in prepared:
        if row.text == "":
            cy += 16
            continue
        if row.quote and q_start is None:
            q_start = cy + 3
            cy += 7
        if not row.quote and q_start is not None and q_end is None:
            q_end = cy + (30 if collapsed_quote else 0)
            cy += 38 if collapsed_quote else 8
        cy += LINE_H * len(lines)
    if q_start is None:
        return None
    if q_end is None:
        q_end = cy + (30 if collapsed_quote else 2)
    return q_start, q_end


def draw_quote_box(
    draw: ImageDraw.ImageDraw, q_start: int, q_end: int, *, collapsed: bool
) -> None:
    left = BUBBLE_X + PAD
    right = BUBBLE_X + BUBBLE_W - PAD
    draw.rounded_rectangle((left, q_start - 5, right, q_end + 2), radius=5, fill=QUOTE_BG)
    draw.rounded_rectangle((left, q_start - 5, left + 5, q_end + 2), radius=3, fill=QUOTE_BAR)
    if collapsed:
        # Fade the last ~28px so the collapse looks like Telegram's clip.
        fade_top = q_end - 28
        for i in range(28):
            alpha = int(18 + i * 6)
            overlay = Image.new("RGBA", (right - left, 1), (*_hex(QUOTE_BG), min(alpha, 210)))
            # Pillow ImageDraw has no alpha on RGB canvas; approximate with a tinted line.
            mix = _mix(QUOTE_BG, BUBBLE, i / 40)
            draw.line((left + 5, fade_top + i, right - 1, fade_top + i), fill=mix)


def _hex(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def _mix(a: str, b: str, t: float) -> tuple[int, int, int]:
    ar, ag, ab = _hex(a)
    br, bg, bb = _hex(b)
    return (
        int(ar + (br - ar) * t),
        int(ag + (bg - ag) * t),
        int(ab + (bb - ab) * t),
    )


def draw_body(
    draw: ImageDraw.ImageDraw,
    y: int,
    prepared: list[tuple[Row, list[str]]],
    *,
    collapsed_quote: bool,
) -> None:
    cy = y + 45
    prev_quote = False
    for row, lines in prepared:
        if row.text == "":
            cy += 16
            prev_quote = row.quote
            continue
        if row.quote and not prev_quote:
            cy += 7
        elif not row.quote and prev_quote:
            cy += 38 if collapsed_quote else 8
        font = F_BOLD if row.bold else F_REG
        inset = 10 if row.quote else 0
        for line in lines:
            draw_rtl(draw, BUBBLE_X + BUBBLE_W - PAD - inset, cy, line, font)
            cy += LINE_H
        prev_quote = row.quote


def draw_expand_affordance(draw: ImageDraw.ImageDraw, q_end: int) -> None:
    label = "نمایش بیشتر"
    draw_rtl(draw, BUBBLE_X + BUBBLE_W - PAD - 12, q_end - 27, label, F_CAPTION, fill=SENDER)
    label_w = visual_width(draw, label, F_CAPTION)
    cx = BUBBLE_X + BUBBLE_W - PAD - 20 - int(label_w)
    yy = q_end - 16
    draw.line((cx - 5, yy - 3, cx, yy + 2, cx + 5, yy - 3), fill=SENDER, width=2)


def draw_bubble(
    draw: ImageDraw.ImageDraw,
    y: int,
    rows: list[Row],
    *,
    timestamp: str = "۱۷:۲۰",
    collapsed_quote: bool = False,
) -> int:
    prepared = prepare_rows(draw, rows, collapsed_quote=collapsed_quote)
    height = measure(prepared, collapsed_quote=collapsed_quote)
    x = BUBBLE_X
    draw.rounded_rectangle((x, y, x + BUBBLE_W, y + height), radius=25, fill=BUBBLE)
    draw_tail(draw, x, y + height)
    draw.text((x + PAD, y + 11), "charbot", font=F_SENDER, fill=SENDER)

    span = quote_span(y, prepared, collapsed_quote=collapsed_quote)
    if span:
        draw_quote_box(draw, span[0], span[1], collapsed=collapsed_quote)
    draw_body(draw, y, prepared, collapsed_quote=collapsed_quote)
    if span and collapsed_quote:
        draw_expand_affordance(draw, span[1])

    draw_rtl(draw, x + BUBBLE_W - 20, y + height - 27, timestamp, F_TIME, fill=MUTED)
    draw_avatar(draw, y + height - 26)
    return y + height


def draw_buttons(draw: ImageDraw.ImageDraw, y: int, buttons: list[str]) -> int:
    # Telegram lays the first reply button on the right in an RTL chat.
    labels = list(reversed(buttons))
    gap = 5
    bh = 55
    bw = (BUBBLE_W - gap * 2) // 3
    for i, label in enumerate(labels):
        bx = BUBBLE_X + i * (bw + gap)
        draw.rounded_rectangle((bx, y, bx + bw, y + bh), radius=9, fill=BUTTON)
        draw.text((bx + bw / 2, y + bh / 2 + 1), shape(label), font=F_BUTTON, fill=TEXT, anchor="mm")
    return y + bh


def canvas(height: int) -> tuple[Image.Image, ImageDraw.ImageDraw]:
    im = Image.new("RGB", (W, height), BG)
    d = ImageDraw.Draw(im)
    d.rectangle((0, 0, W, 58), fill=TOP)
    d.ellipse((22, 15, 52, 45), fill="#8e9aaa")
    d.rounded_rectangle((72, 17, 274, 27), 5, fill="#526170")
    d.rounded_rectangle((72, 34, 188, 41), 4, fill="#344352")
    d.ellipse((934, 17, 940, 23), fill=MUTED)
    d.ellipse((948, 17, 954, 23), fill=MUTED)
    d.ellipse((962, 17, 968, 23), fill=MUTED)
    return im, d


def render_first(data: dict[str, tuple[list[Row], list[str]]]) -> None:
    im, d = canvas(1300)
    y = 82
    y = draw_bubble(d, y, data["digest"][0])
    y += 18
    y = draw_bubble(d, y, data["active"][0])
    y = draw_buttons(d, y + 7, data["active"][1])
    y += 34
    draw_rtl(d, BUBBLE_X + BUBBLE_W, y, "پس از لمس", F_CAPTION, fill=MUTED)
    d.line((BUBBLE_X, y + 25, BUBBLE_X + BUBBLE_W, y + 25), fill=DIVIDER, width=1)
    y += 39
    y = draw_bubble(d, y, data["resolved"][0])
    im.crop((0, 0, W, y + 36)).save(OUT1, optimize=True)


def render_second(data: dict[str, tuple[list[Row], list[str]]]) -> None:
    im, d = canvas(1200)
    y = 82
    y = draw_bubble(d, y, data["daily"][0])
    y += 22
    y = draw_bubble(d, y, data["weekly"][0], collapsed_quote=True)
    im.crop((0, 0, W, y + 36)).save(OUT2, optimize=True)


def main() -> None:
    raw = SOURCE.read_text(encoding="utf-8")
    blocks = {
        "daily": section(raw, "1", "DAILY PLAN"),
        "digest": section(raw, "2", "DIGEST"),
        "active": section(raw, "3", "ACTIVE CARD"),
        "resolved": section(raw, "4", "RESOLVED EDIT"),
        "weekly": section(raw, "5", "WEEKLY REPORT"),
    }
    data = {key: parse_rows(value) for key, value in blocks.items()}
    render_first(data)
    render_second(data)
    print(OUT1)
    print(OUT2)


if __name__ == "__main__":
    main()
